### ISSUE TITLE
Ruby role needs love!

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-ruby#22]
I'm now in the progress of learning Ruby - as one of the eight languages I'm committed to becoming competent in.

I've also identified this role is both outdated and needs lots of love.

This list will attribute to the upcoming release - feel free to add stuff as I want this to be as freakishly awesome as possible!

* [x] #14 - Remove GPG key on cleanup
* [x] #18 - Fix OSX builds
* [x] #19 - Update default version numbers
* [x] #20 - Travis modernization
* [x] #21 - Idempotence
* [x] #23 - Consolidate OS-specific files. 
* [x] #24 - Allow configuration for autolibs (intended for avoiding problems with CI tests).
* [x] #25 - Documentation to reflect changes.
* [ ] General clean-up, flag additional issues as we see fit.
